// <auto-generated />
using System;
using Insyte.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Insyte.Infrastructure.Migrations
{
    [DbContext(typeof(InsyteDbContext))]
    [Migration("20260414214659_AddEvaluationCriteriaAndQuestions")]
    partial class AddEvaluationCriteriaAndQuestions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Insyte.Core.Entities.AIModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AIProviderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxTokens")
                        .HasColumnType("integer");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AIProviderId");

                    b.ToTable("AIModels");
                });

            modelBuilder.Entity("Insyte.Core.Entities.AIProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .HasColumnType("text");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AIProviders");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "Name");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Insyte.Core.Entities.EmailConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecipientName")
                        .HasColumnType("text");

                    b.Property<string>("RecipientType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("EmailConfigs");
                });

            modelBuilder.Entity("Insyte.Core.Entities.EmailLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("EmailLogs");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Evaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AIModelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CriteriaId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("Result")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TokenUsageInput")
                        .HasColumnType("integer");

                    b.Property<int>("TokenUsageOutput")
                        .HasColumnType("integer");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AIModelId");

                    b.HasIndex("CriteriaId");

                    b.HasIndex("VideoId");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("Insyte.Core.Entities.EvaluationCriteria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("EvaluationCriteria");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dersin yapısı, hedef belirleme, müfredatla uyum, konuyu doğru aktarma",
                            Instructions = "Öğretmenin ders planını oluşturma, hedefler belirleme ve müfredata uygun içerik sunma becerisini değerlendirin.",
                            IsActive = true,
                            Name = "Pedagojik Yeterlilik"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ses tonu, konuşma hızı, beden dili, göz teması, dil kullanımı",
                            Instructions = "Öğretmenin iletişim stilini, konuşma netliğini, beden dilini ve sınıf içinde etkileşim kurma becerilerini değerlendirin.",
                            IsActive = true,
                            Name = "İletişim & Sunum Becerileri"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Öğrencileri derse dahil etme, sorular sorma, ilgiyi canlı tutma",
                            Instructions = "Öğrencilerin derse katılım düzeyini, motivasyon seviyesini ve öğretmenin etkileşim kurma çabalarını değerlendirin.",
                            IsActive = true,
                            Name = "Öğrenci Katılımı & Motivasyonu"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Düzeni sağlama, zaman yönetimi, disiplin yaklaşımı",
                            Instructions = "Sınıf düzeninin sağlanması, zamanın etkili kullanılması ve disiplin yaklaşımının uygunluğunu değerlendirin.",
                            IsActive = true,
                            Name = "Sınıf Yönetimi"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Öğrenci sorularını yanıtlama, anlık geri bildirim, yönlendirme",
                            Instructions = "Öğrenci sorularına verilen cevapların kalitesini, geri bildirim etkinliğini ve yapıcı yönlendirmeyi değerlendirin.",
                            IsActive = true,
                            Name = "Soru-Cevap & Geri Bildirim Kalitesi"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tahta, slayt, araç-gereç kullanımı, materyallerin etkinliği",
                            Instructions = "Öğretim materyallerinin uygunluğunu, çeşitliliğini ve etkili kullanımını değerlendirin.",
                            IsActive = true,
                            Name = "Materyal & Görsel Kullanımı"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Farklı öğrenme düzeylerine hitap etme, bireysel ilgi",
                            Instructions = "Öğretmenin farklı öğrenme stillerine ve seviyelere uygun öğretim stratejileri kullanıp kullanmadığını değerlendirin.",
                            IsActive = true,
                            Name = "Farklılaştırılmış Öğretim"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Öğrencilerin ilgi düzeyi, katılım, beden dili, motivasyon",
                            Instructions = "Öğrencilerin derste gösterdikleri ilgi, katılım düzeyi, beden dilini ve genel motivasyon durumunu değerlendirin.",
                            IsActive = true,
                            Name = "Öğrenci Davranışı & Tepkileri"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Konuyu doğru ve anlaşılır aktarma, yanlış bilgi var mı",
                            Instructions = "Öğretmenin konuyu doğru bir şekilde anlatan, yanlış bilgi içermeyen ve anlaşılır bir dil kullanıp kullanmadığını değerlendirin.",
                            IsActive = true,
                            Name = "Dil & Kavram Doğruluğu"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Başlangıç-orta-kapanış dengesi, geçişler, süre yönetimi",
                            Instructions = "Dersin başlangıcından sonuna kadar akışını, geçişlerin uygunluğunu ve zamanın dengeli kullanılıp kullanılmadığını değerlendirin.",
                            IsActive = true,
                            Name = "Genel Ders Akışı & Tempo"
                        });
                });

            modelBuilder.Entity("Insyte.Core.Entities.EvaluationQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CriteriaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CriteriaId", "Order");

                    b.ToTable("EvaluationQuestions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fc1af23b-d290-49cc-ba16-55e2717b8c33"),
                            Category = "🗣️ İletişim & Ses",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 1,
                            Question = "Öğretmenin sesi net ve anlaşılır mı, yoksa çok alçak/yüksek mi konuşuyor?"
                        },
                        new
                        {
                            Id = new Guid("12c2d448-e9fd-433a-8601-6d5f235786e9"),
                            Category = "🗣️ İletişim & Ses",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 2,
                            Question = "Konuşma hızı uygun mu — çok hızlı veya çok yavaş mı?"
                        },
                        new
                        {
                            Id = new Guid("bc6eca6f-edc8-4a9c-b1c1-f7b9e0b5b0af"),
                            Category = "🗣️ İletişim & Ses",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 3,
                            Question = "Öğretmen monoton mu konuşuyor, yoksa ses tonunda çeşitlilik var mı?"
                        },
                        new
                        {
                            Id = new Guid("90d513e8-9694-4148-acb1-d94594828e78"),
                            Category = "🗣️ İletişim & Ses",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 4,
                            Question = "Önemli kavramları vurgularken ses tonunu değiştiriyor mu?"
                        },
                        new
                        {
                            Id = new Guid("1570409a-824d-42a1-827e-57fd81c49398"),
                            Category = "🗣️ İletişim & Ses",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 5,
                            Question = "Türkçeyi (ya da ders dilini) doğru ve akıcı kullanıyor mu?"
                        },
                        new
                        {
                            Id = new Guid("1ba857aa-949d-463e-81a6-162e1a2eb927"),
                            Category = "🗣️ İletişim & Ses",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 6,
                            Question = "Gereksiz dolgu sözler (yani, şey, hmm) ne sıklıkla kullanılıyor?"
                        },
                        new
                        {
                            Id = new Guid("20b53b68-42eb-4c2a-a38e-333c7a0381bd"),
                            Category = "🗣️ İletişim & Ses",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 7,
                            Question = "Öğrencilere hitap ederken ne kadar samimi ve sıcak bir ton kullanıyor?"
                        },
                        new
                        {
                            Id = new Guid("7bc3a583-cad7-4eab-9223-c58acb5f4bba"),
                            Category = "🧍 Beden Dili & Fiziksel Varlık",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 8,
                            Question = "Öğretmen sınıfı aktif olarak dolaşıyor mu, yoksa tek noktada mı duruyor?"
                        },
                        new
                        {
                            Id = new Guid("0823e929-60b9-4afc-8967-3ed2253f4300"),
                            Category = "🧍 Beden Dili & Fiziksel Varlık",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 9,
                            Question = "Göz teması kuruyor mu — sadece tahtaya mı bakıyor, öğrencilere mi?"
                        },
                        new
                        {
                            Id = new Guid("9a145f43-890a-4ba4-8378-d9f5f650cb0b"),
                            Category = "🧍 Beden Dili & Fiziksel Varlık",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 10,
                            Question = "El, kol hareketleri anlatımı destekliyor mu?"
                        },
                        new
                        {
                            Id = new Guid("7e3963b7-eda3-4415-9b7e-b11a7a4bd62d"),
                            Category = "🧍 Beden Dili & Fiziksel Varlık",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 11,
                            Question = "Öğrencilere karşı açık ve davetkar bir duruş mu sergiliyor?"
                        },
                        new
                        {
                            Id = new Guid("b048c402-5833-43d5-9f2c-9e804d300a2c"),
                            Category = "🧍 Beden Dili & Fiziksel Varlık",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 12,
                            Question = "Yüz ifadeleri anlatılanlarla uyumlu mu?"
                        },
                        new
                        {
                            Id = new Guid("795e3b40-a8f2-4b2e-aab2-4d5e5de32ce9"),
                            Category = "📚 Pedagoji & Ders İçeriği",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Order = 13,
                            Question = "Dersin başında öğrencilere neyi öğreneceklerini açıklıyor mu?"
                        },
                        new
                        {
                            Id = new Guid("70736b3f-672f-474c-9a7c-fae3301642ba"),
                            Category = "📚 Pedagoji & Ders İçeriği",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Order = 14,
                            Question = "Konu anlatımı mantıksal bir sırayla ilerliyor mu?"
                        },
                        new
                        {
                            Id = new Guid("72153382-9a12-468e-87a6-6967181c04e5"),
                            Category = "📚 Pedagoji & Ders İçeriği",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Order = 15,
                            Question = "Öğrettiği bilgiler doğru mu — kavram veya bilgi hatası var mı?"
                        },
                        new
                        {
                            Id = new Guid("9ff67be6-7baf-41f7-8a75-beedc04e2af7"),
                            Category = "📚 Pedagoji & Ders İçeriği",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Order = 16,
                            Question = "Konuyu günlük hayatla ilişkilendiriyor mu, somut örnekler veriyor mu?"
                        },
                        new
                        {
                            Id = new Guid("d1a6b3ea-e6f1-4e2c-a0a3-1e70a3f1f63b"),
                            Category = "📚 Pedagoji & Ders İçeriği",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Order = 17,
                            Question = "Karmaşık kavramları basitten karmaşığa doğru açıklıyor mu?"
                        },
                        new
                        {
                            Id = new Guid("4285c477-f0eb-4130-83de-aa636b738b7e"),
                            Category = "📚 Pedagoji & Ders İçeriği",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Order = 18,
                            Question = "Önceki derslerle bağlantı kuruyor mu?"
                        },
                        new
                        {
                            Id = new Guid("1ded10a3-817a-438a-b6fe-6fa97b7242dd"),
                            Category = "📚 Pedagoji & Ders İçeriği",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Order = 19,
                            Question = "Ders sonunda özet ya da tekrar yapıyor mu?"
                        },
                        new
                        {
                            Id = new Guid("ec0099df-5200-415f-9d22-f79fe2382985"),
                            Category = "📚 Pedagoji & Ders İçeriği",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Order = 20,
                            Question = "Ders hedefine ulaşıldı mı — dersin sonunda öğrenciler konuyu anlamış görünüyor mu?"
                        },
                        new
                        {
                            Id = new Guid("f41ca638-9007-4844-a009-dd1be26ddc64"),
                            Category = "🙋 Öğrenci Katılımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Order = 21,
                            Question = "Öğrencilere ne sıklıkla soru soruyor?"
                        },
                        new
                        {
                            Id = new Guid("602f1645-eb12-4ca5-a8ec-6c266f69e001"),
                            Category = "🙋 Öğrenci Katılımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Order = 22,
                            Question = "Soruları sadece belli öğrencilere mi, yoksa tüm sınıfa mı yöneltiyor?"
                        },
                        new
                        {
                            Id = new Guid("b031a62c-6fea-4515-8275-ef74d9f1787b"),
                            Category = "🙋 Öğrenci Katılımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Order = 23,
                            Question = "Öğrencilere düşünme zamanı (bekleme süresi) veriyor mu?"
                        },
                        new
                        {
                            Id = new Guid("ddc37151-c9b2-4669-8eaf-6e1edf1be9a7"),
                            Category = "🙋 Öğrenci Katılımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Order = 24,
                            Question = "Öğrenci cevaplarını dinliyor mu, yoksa cevabı kendisi mi tamamlıyor?"
                        },
                        new
                        {
                            Id = new Guid("3f3084c9-3ba8-4987-b6eb-4da114ce9c80"),
                            Category = "🙋 Öğrenci Katılımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Order = 25,
                            Question = "Öğrencilerin birbirini dinlemesini ve tartışmasını teşvik ediyor mu?"
                        },
                        new
                        {
                            Id = new Guid("effec866-edc6-491c-bc1f-aa7e9f248b1b"),
                            Category = "🙋 Öğrenci Katılımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Order = 26,
                            Question = "Gönüllü olmayan öğrencileri derse nasıl dahil ediyor?"
                        },
                        new
                        {
                            Id = new Guid("ec9c63b4-774c-44b7-a0dd-8b1cc3efe3e8"),
                            Category = "🙋 Öğrenci Katılımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Order = 27,
                            Question = "Grup çalışması ya da işbirlikli öğrenme var mı?"
                        },
                        new
                        {
                            Id = new Guid("95d9ef26-014e-4cf8-bfba-ee9fd087c040"),
                            Category = "🙋 Öğrenci Katılımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Order = 28,
                            Question = "Öğrencilerin kendi fikirlerini ifade etmelerine alan açıyor mu?"
                        },
                        new
                        {
                            Id = new Guid("4e342c4d-3016-4478-b8fa-762880ef19f6"),
                            Category = "💬 Geri Bildirim & Soru-Cevap",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            Order = 29,
                            Question = "Öğrenci cevapları doğru olduğunda nasıl geri bildirim veriyor?"
                        },
                        new
                        {
                            Id = new Guid("bb5d7216-1ce3-4849-839a-07997782348b"),
                            Category = "💬 Geri Bildirim & Soru-Cevap",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            Order = 30,
                            Question = "Yanlış cevaplarda öğrenciyi küçük düşürüyor mu, yoksa yapıcı mı yaklaşıyor?"
                        },
                        new
                        {
                            Id = new Guid("0d160b27-865d-4134-91ec-c52704c29f36"),
                            Category = "💬 Geri Bildirim & Soru-Cevap",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            Order = 31,
                            Question = "Öğrencinin sorusunu doğru anlayıp yanıtlıyor mu?"
                        },
                        new
                        {
                            Id = new Guid("b4bfdad0-09ff-4122-aa36-4df4333e4c54"),
                            Category = "💬 Geri Bildirim & Soru-Cevap",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            Order = 32,
                            Question = "Cevabı bilmeyen öğrenciye nasıl yaklaşıyor?"
                        },
                        new
                        {
                            Id = new Guid("cc869755-0bc3-4193-b2cf-e9fb768e81b2"),
                            Category = "💬 Geri Bildirim & Soru-Cevap",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            Order = 33,
                            Question = "Geri bildirimler spesifik mi (\"aferin\" gibi genel mi, yoksa \"şunu iyi yaptın çünkü…\" gibi açıklayıcı mı)?"
                        },
                        new
                        {
                            Id = new Guid("1549b195-3c01-45d9-9c98-efb2b696a8fb"),
                            Category = "💬 Geri Bildirim & Soru-Cevap",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            Order = 34,
                            Question = "Öğrencilerin anladığını nasıl kontrol ediyor — anlama soruları soruyor mu?"
                        },
                        new
                        {
                            Id = new Guid("7725d37b-87a8-42db-a426-6f6579506336"),
                            Category = "🏫 Sınıf Yönetimi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Order = 35,
                            Question = "Sınıfta genel düzen ve sessizlik sağlanabiliyor mu?"
                        },
                        new
                        {
                            Id = new Guid("d8da1678-c2a8-45ac-9b4a-d3072871f9ca"),
                            Category = "🏫 Sınıf Yönetimi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Order = 36,
                            Question = "Derse odaklanamayan ya da konuşan öğrencilerle nasıl başa çıkıyor?"
                        },
                        new
                        {
                            Id = new Guid("a3627758-cfb1-4467-a6f0-c0345d5e295a"),
                            Category = "🏫 Sınıf Yönetimi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Order = 37,
                            Question = "Disiplin müdahalesi varsa nasıl yapılıyor — saygılı mı, agresif mi?"
                        },
                        new
                        {
                            Id = new Guid("0b1ab1f9-372f-4b33-8c87-a24014840883"),
                            Category = "🏫 Sınıf Yönetimi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Order = 38,
                            Question = "Zamanı iyi yönetiyor mu — ders planladığı gibi ilerliyor mu?"
                        },
                        new
                        {
                            Id = new Guid("6d5e6acf-e597-4dc7-b962-5d9bb90f2881"),
                            Category = "🏫 Sınıf Yönetimi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Order = 39,
                            Question = "Geçişler (yeni konuya geçiş, aktivite değişimi) pürüzsüz mü?"
                        },
                        new
                        {
                            Id = new Guid("f28aae8b-d0d5-4d60-8588-f05aa382dd89"),
                            Category = "🏫 Sınıf Yönetimi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Order = 40,
                            Question = "Beklenmedik durumlara (teknik sorun, öğrenci sorusu, vs.) nasıl tepki veriyor?"
                        },
                        new
                        {
                            Id = new Guid("0382c84e-b82c-490f-b626-a794fe98600b"),
                            Category = "🖥️ Materyal & Araç Kullanımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000006"),
                            IsActive = true,
                            Order = 41,
                            Question = "Kullanılan materyaller (slayt, tahta, video, vs.) içerikle uyumlu ve kaliteli mi?"
                        },
                        new
                        {
                            Id = new Guid("8d793010-a9a1-4697-8485-dbf677147708"),
                            Category = "🖥️ Materyal & Araç Kullanımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000006"),
                            IsActive = true,
                            Order = 42,
                            Question = "Tahtayı/ekranı düzenli ve okunabilir şekilde mi kullanıyor?"
                        },
                        new
                        {
                            Id = new Guid("8b7cf1a6-a1f9-46fa-bd04-6655b20dea5a"),
                            Category = "🖥️ Materyal & Araç Kullanımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000006"),
                            IsActive = true,
                            Order = 43,
                            Question = "Görsel materyaller öğrenmeyi destekliyor mu, yoksa dikkat dağıtıyor mu?"
                        },
                        new
                        {
                            Id = new Guid("60c6b183-3c5d-4dd2-bf83-ef2c8657313e"),
                            Category = "🖥️ Materyal & Araç Kullanımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000006"),
                            IsActive = true,
                            Order = 44,
                            Question = "Teknolojiyi etkin mi kullanıyor?"
                        },
                        new
                        {
                            Id = new Guid("ae8ad6ad-5196-4ab4-9344-4b6bc850ac6d"),
                            Category = "🖥️ Materyal & Araç Kullanımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000006"),
                            IsActive = true,
                            Order = 45,
                            Question = "Materyaller tüm öğrencilerin görebileceği şekilde konumlandırılmış mı?"
                        },
                        new
                        {
                            Id = new Guid("a8dd6e2d-fe9f-4d0a-a420-d2f6a74cd37c"),
                            Category = "👥 Öğrenci Davranışı & Sınıf Atmosferi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsActive = true,
                            Order = 46,
                            Question = "Öğrencilerin genel ilgi ve odaklanma düzeyi nasıl?"
                        },
                        new
                        {
                            Id = new Guid("21fe0584-e49d-4a9c-88a3-7a1b5a79363f"),
                            Category = "👥 Öğrenci Davranışı & Sınıf Atmosferi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsActive = true,
                            Order = 47,
                            Question = "Öğrenciler ders sırasında ne yapıyor — not mu alıyor, telefonla mı ilgileniyor, konuşuyor mu?"
                        },
                        new
                        {
                            Id = new Guid("0dbf2d51-1dfa-4557-99f7-f613a4ad19d4"),
                            Category = "👥 Öğrenci Davranışı & Sınıf Atmosferi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsActive = true,
                            Order = 48,
                            Question = "Öğrencilerin soru sorma ya da katılım istekliliği var mı?"
                        },
                        new
                        {
                            Id = new Guid("7bfa2df8-e0de-491d-833d-ae1edaf36933"),
                            Category = "👥 Öğrenci Davranışı & Sınıf Atmosferi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsActive = true,
                            Order = 49,
                            Question = "Sınıfta pozitif, güvenli bir öğrenme ortamı var mı?"
                        },
                        new
                        {
                            Id = new Guid("c524dbe8-e652-4efc-bbda-174f67746268"),
                            Category = "👥 Öğrenci Davranışı & Sınıf Atmosferi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsActive = true,
                            Order = 50,
                            Question = "Öğretmen-öğrenci ilişkisi nasıl görünüyor — saygılı, mesafeli, sıcak?"
                        },
                        new
                        {
                            Id = new Guid("7cc01e21-d27d-4ec8-8369-66dba9d50175"),
                            Category = "👥 Öğrenci Davranışı & Sınıf Atmosferi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsActive = true,
                            Order = 51,
                            Question = "Öğrencilerin yüz ifadeleri ve beden dili neler söylüyor — sıkılmış mı, meraklı mı?"
                        },
                        new
                        {
                            Id = new Guid("5d05a810-f146-4d19-9a1d-8375d612fbe8"),
                            Category = "👥 Öğrenci Davranışı & Sınıf Atmosferi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsActive = true,
                            Order = 52,
                            Question = "Dersin hangi anlarında öğrenci enerjisi yükseliyor ya da düşüyor?"
                        },
                        new
                        {
                            Id = new Guid("6d7690eb-a98d-4bc3-b717-709328d911de"),
                            Category = "🌍 Kapsayıcılık & Farklılaştırma",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000007"),
                            IsActive = true,
                            Order = 53,
                            Question = "Farklı öğrenme hızlarındaki öğrencilere uyum sağlıyor mu?"
                        },
                        new
                        {
                            Id = new Guid("d2a9a0ce-c61a-4617-833c-a253589dc3fb"),
                            Category = "🌍 Kapsayıcılık & Farklılaştırma",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000007"),
                            IsActive = true,
                            Order = 54,
                            Question = "Öğrenme güçlüğü çeken öğrenciye özel ilgi gösteriyor mu?"
                        },
                        new
                        {
                            Id = new Guid("9db1a10d-5730-4211-a06a-2b2dbf4e34d4"),
                            Category = "🌍 Kapsayıcılık & Farklılaştırma",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000007"),
                            IsActive = true,
                            Order = 55,
                            Question = "Tüm öğrencilere eşit mesafede mi davranıyor, favoriler var mı?"
                        },
                        new
                        {
                            Id = new Guid("1cd04f93-bec7-4884-ab21-0c68c68c1650"),
                            Category = "🔄 Genel Ders Değerlendirmesi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000010"),
                            IsActive = true,
                            Order = 56,
                            Question = "Bu dersi izleyen biri ne öğrendiğini açıklayabilir mi?"
                        },
                        new
                        {
                            Id = new Guid("836b3644-9d48-42f6-b08f-cd1938ec0645"),
                            Category = "🔄 Genel Ders Değerlendirmesi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000010"),
                            IsActive = true,
                            Order = 57,
                            Question = "Ders tekrar izlenmeli miydi, yoksa tek seferde anlaşılır mıydı?"
                        },
                        new
                        {
                            Id = new Guid("5219b2d1-117a-46f0-9f12-5d8bed792945"),
                            Category = "🔄 Genel Ders Değerlendirmesi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000010"),
                            IsActive = true,
                            Order = 58,
                            Question = "Öğretmenin en güçlü 3 yönü nedir?"
                        },
                        new
                        {
                            Id = new Guid("d5124406-5e77-43ba-94e5-fbff4e07552e"),
                            Category = "🔄 Genel Ders Değerlendirmesi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000010"),
                            IsActive = true,
                            Order = 59,
                            Question = "Öğretmenin gelişim alanları nelerdir — somut önerilerle?"
                        },
                        new
                        {
                            Id = new Guid("d94b00a5-174c-417c-a721-ac74b02f2d19"),
                            Category = "🔄 Genel Ders Değerlendirmesi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000010"),
                            IsActive = true,
                            Order = 60,
                            Question = "Bu ders için genel bir başarı puanı verilseydi ne olurdu (1-10)?"
                        },
                        new
                        {
                            Id = new Guid("52f9c5da-aaff-47b3-97b8-7a4f752ae100"),
                            Category = "🔄 Genel Ders Değerlendirmesi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000010"),
                            IsActive = true,
                            Order = 61,
                            Question = "Bir sonraki derste öncelikli olarak iyileştirilmesi gereken tek şey ne?"
                        });
                });

            modelBuilder.Entity("Insyte.Core.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PdfPath")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("EvaluationId")
                        .IsUnique();

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Room")
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherUserId");

                    b.HasIndex("ClassId", "DayOfWeek", "StartTime");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Insyte.Core.Entities.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EducationSystem")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("InstitutionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LiseType")
                        .HasColumnType("text");

                    b.Property<string>("LogoPath")
                        .HasColumnType("text");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("SchoolType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "Activity")
                        .IsUnique();

                    b.ToTable("SchoolActivities");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolAdvisor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("SchoolId", "UserId")
                        .IsUnique();

                    b.ToTable("SchoolAdvisors");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolFacility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Facility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "Facility")
                        .IsUnique();

                    b.ToTable("SchoolFacilities");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "Language")
                        .IsUnique();

                    b.ToTable("SchoolLanguages");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolServiceOffering", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "Service")
                        .IsUnique();

                    b.ToTable("SchoolServices");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("SchoolId", "UserId")
                        .IsUnique();

                    b.ToTable("SchoolUsers");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WeeklyHours")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "Name");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Insyte.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@insyte.com",
                            FirstName = "System",
                            IsActive = true,
                            LastName = "Admin",
                            PasswordHash = "$2a$11$2PfOtcqfnVBIePYTn4cJUejLkv0CFekraRflHRPg6mahWjkQRlHt.",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("Insyte.Core.Entities.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.Property<Guid>("TeacherUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("TeacherUserId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("Insyte.Core.Entities.AIModel", b =>
                {
                    b.HasOne("Insyte.Core.Entities.AIProvider", "AIProvider")
                        .WithMany("Models")
                        .HasForeignKey("AIProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AIProvider");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Class", b =>
                {
                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("Classes")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Insyte.Core.Entities.EmailConfig", b =>
                {
                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("EmailConfigs")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Insyte.Core.Entities.EmailLog", b =>
                {
                    b.HasOne("Insyte.Core.Entities.Report", "Report")
                        .WithMany("EmailLogs")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Evaluation", b =>
                {
                    b.HasOne("Insyte.Core.Entities.AIModel", "AIModel")
                        .WithMany("Evaluations")
                        .HasForeignKey("AIModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Insyte.Core.Entities.EvaluationCriteria", "Criteria")
                        .WithMany("Evaluations")
                        .HasForeignKey("CriteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Insyte.Core.Entities.Video", "Video")
                        .WithMany("Evaluations")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AIModel");

                    b.Navigation("Criteria");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Insyte.Core.Entities.EvaluationQuestion", b =>
                {
                    b.HasOne("Insyte.Core.Entities.EvaluationCriteria", "Criteria")
                        .WithMany("Questions")
                        .HasForeignKey("CriteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Report", b =>
                {
                    b.HasOne("Insyte.Core.Entities.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Insyte.Core.Entities.Evaluation", "Evaluation")
                        .WithOne("Report")
                        .HasForeignKey("Insyte.Core.Entities.Report", "EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Schedule", b =>
                {
                    b.HasOne("Insyte.Core.Entities.Class", "Class")
                        .WithMany("Schedules")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("Schedules")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Insyte.Core.Entities.Subject", "Subject")
                        .WithMany("Schedules")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Insyte.Core.Entities.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("School");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolActivity", b =>
                {
                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("Activities")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolAdvisor", b =>
                {
                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("Advisors")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Insyte.Core.Entities.User", "User")
                        .WithMany("AdvisedSchools")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolFacility", b =>
                {
                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("Facilities")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolLanguage", b =>
                {
                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("Languages")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolServiceOffering", b =>
                {
                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("Services")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolUser", b =>
                {
                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("Users")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Insyte.Core.Entities.User", "User")
                        .WithMany("SchoolUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Subject", b =>
                {
                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("Subjects")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Video", b =>
                {
                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("Videos")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Insyte.Core.Entities.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Insyte.Core.Entities.User", "UploadedBy")
                        .WithMany("UploadedVideos")
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("Teacher");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("Insyte.Core.Entities.AIModel", b =>
                {
                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("Insyte.Core.Entities.AIProvider", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Class", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Evaluation", b =>
                {
                    b.Navigation("Report");
                });

            modelBuilder.Entity("Insyte.Core.Entities.EvaluationCriteria", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Report", b =>
                {
                    b.Navigation("EmailLogs");
                });

            modelBuilder.Entity("Insyte.Core.Entities.School", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Advisors");

                    b.Navigation("Classes");

                    b.Navigation("EmailConfigs");

                    b.Navigation("Facilities");

                    b.Navigation("Languages");

                    b.Navigation("Schedules");

                    b.Navigation("Services");

                    b.Navigation("Subjects");

                    b.Navigation("Users");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Subject", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Insyte.Core.Entities.User", b =>
                {
                    b.Navigation("AdvisedSchools");

                    b.Navigation("SchoolUsers");

                    b.Navigation("UploadedVideos");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Video", b =>
                {
                    b.Navigation("Evaluations");
                });
#pragma warning restore 612, 618
        }
    }
}
