// <auto-generated />
using System;
using Insyte.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Insyte.Infrastructure.Migrations
{
    [DbContext(typeof(InsyteDbContext))]
    partial class InsyteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Insyte.Core.Entities.AIModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AIProviderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxTokens")
                        .HasColumnType("integer");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AIProviderId");

                    b.ToTable("AIModels");
                });

            modelBuilder.Entity("Insyte.Core.Entities.AIProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .HasColumnType("text");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AIProviders");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "Name");

                    b.ToTable("Classes");
                });


            modelBuilder.Entity("Insyte.Core.Entities.EmailConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecipientName")
                        .HasColumnType("text");

                    b.Property<string>("RecipientType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("EmailConfigs");
                });

            modelBuilder.Entity("Insyte.Core.Entities.EmailLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("EmailLogs");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Evaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AIModelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CriteriaId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("Result")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TokenUsageInput")
                        .HasColumnType("integer");

                    b.Property<int>("TokenUsageOutput")
                        .HasColumnType("integer");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AIModelId");

                    b.HasIndex("CriteriaId");

                    b.HasIndex("VideoId");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("Insyte.Core.Entities.EvaluationCriteria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("EvaluationCriteria");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dersin yapısı, hedef belirleme, müfredatla uyum, konuyu doğru aktarma",
                            Instructions = "Öğretmenin ders planını oluşturma, hedefler belirleme ve müfredata uygun içerik sunma becerisini değerlendirin.",
                            IsActive = true,
                            Name = "Pedagojik Yeterlilik"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ses tonu, konuşma hızı, beden dili, göz teması, dil kullanımı",
                            Instructions = "Öğretmenin iletişim stilini, konuşma netliğini, beden dilini ve sınıf içinde etkileşim kurma becerilerini değerlendirin.",
                            IsActive = true,
                            Name = "İletişim & Sunum Becerileri"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Öğrencileri derse dahil etme, sorular sorma, ilgiyi canlı tutma",
                            Instructions = "Öğrencilerin derse katılım düzeyini, motivasyon seviyesini ve öğretmenin etkileşim kurma çabalarını değerlendirin.",
                            IsActive = true,
                            Name = "Öğrenci Katılımı & Motivasyonu"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Düzeni sağlama, zaman yönetimi, disiplin yaklaşımı",
                            Instructions = "Sınıf düzeninin sağlanması, zamanın etkili kullanılması ve disiplin yaklaşımının uygunluğunu değerlendirin.",
                            IsActive = true,
                            Name = "Sınıf Yönetimi"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Öğrenci sorularını yanıtlama, anlık geri bildirim, yönlendirme",
                            Instructions = "Öğrenci sorularına verilen cevapların kalitesini, geri bildirim etkinliğini ve yapıcı yönlendirmeyi değerlendirin.",
                            IsActive = true,
                            Name = "Soru-Cevap & Geri Bildirim Kalitesi"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tahta, slayt, araç-gereç kullanımı, materyallerin etkinliği",
                            Instructions = "Öğretim materyallerinin uygunluğunu, çeşitliliğini ve etkili kullanımını değerlendirin.",
                            IsActive = true,
                            Name = "Materyal & Görsel Kullanımı"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Farklı öğrenme düzeylerine hitap etme, bireysel ilgi",
                            Instructions = "Öğretmenin farklı öğrenme stillerine ve seviyelere uygun öğretim stratejileri kullanıp kullanmadığını değerlendirin.",
                            IsActive = true,
                            Name = "Farklılaştırılmış Öğretim"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Öğrencilerin ilgi düzeyi, katılım, beden dili, motivasyon",
                            Instructions = "Öğrencilerin derste gösterdikleri ilgi, katılım düzeyi, beden dilini ve genel motivasyon durumunu değerlendirin.",
                            IsActive = true,
                            Name = "Öğrenci Davranışı & Tepkileri"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Konuyu doğru ve anlaşılır aktarma, yanlış bilgi var mı",
                            Instructions = "Öğretmenin konuyu doğru bir şekilde anlatan, yanlış bilgi içermeyen ve anlaşılır bir dil kullanıp kullanmadığını değerlendirin.",
                            IsActive = true,
                            Name = "Dil & Kavram Doğruluğu"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Başlangıç-orta-kapanış dengesi, geçişler, süre yönetimi",
                            Instructions = "Dersin başlangıcından sonuna kadar akışını, geçişlerin uygunluğunu ve zamanın dengeli kullanılıp kullanılmadığını değerlendirin.",
                            IsActive = true,
                            Name = "Genel Ders Akışı & Tempo"
                        });
                });

            modelBuilder.Entity("Insyte.Core.Entities.EvaluationQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CriteriaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CriteriaId", "Order");

                    b.ToTable("EvaluationQuestions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("058bbde2-3fd0-47fb-b05e-6464900b471f"),
                            Category = "🗣️ İletişim & Ses",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 1,
                            Question = "Öğretmenin sesi net ve anlaşılır mı, yoksa çok alçak/yüksek mi konuşuyor?"
                        },
                        new
                        {
                            Id = new Guid("2963e095-5b1e-4847-a19c-0ea6a8f4d20b"),
                            Category = "🗣️ İletişim & Ses",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 2,
                            Question = "Konuşma hızı uygun mu — çok hızlı veya çok yavaş mı?"
                        },
                        new
                        {
                            Id = new Guid("03552865-15bb-4db9-9378-7f74da68423e"),
                            Category = "🗣️ İletişim & Ses",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 3,
                            Question = "Öğretmen monoton mu konuşuyor, yoksa ses tonunda çeşitlilik var mı?"
                        },
                        new
                        {
                            Id = new Guid("2d0cce69-0687-4354-b89b-7711da049a60"),
                            Category = "🗣️ İletişim & Ses",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 4,
                            Question = "Önemli kavramları vurgularken ses tonunu değiştiriyor mu?"
                        },
                        new
                        {
                            Id = new Guid("3c9f5eef-3ca0-4ee9-b862-cfc505984dd1"),
                            Category = "🗣️ İletişim & Ses",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 5,
                            Question = "Türkçeyi (ya da ders dilini) doğru ve akıcı kullanıyor mu?"
                        },
                        new
                        {
                            Id = new Guid("9ce77b91-0f9a-41a0-9709-0d6fdaa43a42"),
                            Category = "🗣️ İletişim & Ses",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 6,
                            Question = "Gereksiz dolgu sözler (yani, şey, hmm) ne sıklıkla kullanılıyor?"
                        },
                        new
                        {
                            Id = new Guid("76e4a93c-6511-4123-85c6-824e862000d7"),
                            Category = "🗣️ İletişim & Ses",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 7,
                            Question = "Öğrencilere hitap ederken ne kadar samimi ve sıcak bir ton kullanıyor?"
                        },
                        new
                        {
                            Id = new Guid("79dc0e5b-fa1e-4be0-b414-15418a90692e"),
                            Category = "🧍 Beden Dili & Fiziksel Varlık",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 8,
                            Question = "Öğretmen sınıfı aktif olarak dolaşıyor mu, yoksa tek noktada mı duruyor?"
                        },
                        new
                        {
                            Id = new Guid("85dbc5cb-5e78-45f6-bcc1-2b978f35dd00"),
                            Category = "🧍 Beden Dili & Fiziksel Varlık",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 9,
                            Question = "Göz teması kuruyor mu — sadece tahtaya mı bakıyor, öğrencilere mi?"
                        },
                        new
                        {
                            Id = new Guid("7e20f63a-2e79-4a10-9f77-7d935c865037"),
                            Category = "🧍 Beden Dili & Fiziksel Varlık",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 10,
                            Question = "El, kol hareketleri anlatımı destekliyor mu?"
                        },
                        new
                        {
                            Id = new Guid("a019898b-0f58-445e-bf25-132e61d8a010"),
                            Category = "🧍 Beden Dili & Fiziksel Varlık",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 11,
                            Question = "Öğrencilere karşı açık ve davetkar bir duruş mu sergiliyor?"
                        },
                        new
                        {
                            Id = new Guid("f98de439-ca0d-4686-9d95-e6ed3c4fab00"),
                            Category = "🧍 Beden Dili & Fiziksel Varlık",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 12,
                            Question = "Yüz ifadeleri anlatılanlarla uyumlu mu?"
                        },
                        new
                        {
                            Id = new Guid("96bd06ae-9b62-40bf-b32a-dc02a7e7c3f3"),
                            Category = "📚 Pedagoji & Ders İçeriği",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Order = 13,
                            Question = "Dersin başında öğrencilere neyi öğreneceklerini açıklıyor mu?"
                        },
                        new
                        {
                            Id = new Guid("27f6027d-b3e0-4a9e-96c4-7253af85d6e2"),
                            Category = "📚 Pedagoji & Ders İçeriği",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Order = 14,
                            Question = "Konu anlatımı mantıksal bir sırayla ilerliyor mu?"
                        },
                        new
                        {
                            Id = new Guid("32ffffe4-ef90-4f16-9228-a13bc5893a1c"),
                            Category = "📚 Pedagoji & Ders İçeriği",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Order = 15,
                            Question = "Öğrettiği bilgiler doğru mu — kavram veya bilgi hatası var mı?"
                        },
                        new
                        {
                            Id = new Guid("4d8a83c2-ba32-4b0a-b945-26db4cc7dd7a"),
                            Category = "📚 Pedagoji & Ders İçeriği",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Order = 16,
                            Question = "Konuyu günlük hayatla ilişkilendiriyor mu, somut örnekler veriyor mu?"
                        },
                        new
                        {
                            Id = new Guid("e0c6f777-aea8-4304-b903-38317e4a31ee"),
                            Category = "📚 Pedagoji & Ders İçeriği",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Order = 17,
                            Question = "Karmaşık kavramları basitten karmaşığa doğru açıklıyor mu?"
                        },
                        new
                        {
                            Id = new Guid("78cc007a-ac3b-4cac-8548-d68b3c129208"),
                            Category = "📚 Pedagoji & Ders İçeriği",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Order = 18,
                            Question = "Önceki derslerle bağlantı kuruyor mu?"
                        },
                        new
                        {
                            Id = new Guid("17f87281-2043-42c7-add5-6c7ad637d6da"),
                            Category = "📚 Pedagoji & Ders İçeriği",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Order = 19,
                            Question = "Ders sonunda özet ya da tekrar yapıyor mu?"
                        },
                        new
                        {
                            Id = new Guid("6f81f1cc-d418-4f81-9537-d589f6b51141"),
                            Category = "📚 Pedagoji & Ders İçeriği",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Order = 20,
                            Question = "Ders hedefine ulaşıldı mı — dersin sonunda öğrenciler konuyu anlamış görünüyor mu?"
                        },
                        new
                        {
                            Id = new Guid("bc54be87-efaa-44f9-91f6-778d046da8e4"),
                            Category = "🙋 Öğrenci Katılımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Order = 21,
                            Question = "Öğrencilere ne sıklıkla soru soruyor?"
                        },
                        new
                        {
                            Id = new Guid("2628b454-442c-4bae-afb3-33fd2ca06ae4"),
                            Category = "🙋 Öğrenci Katılımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Order = 22,
                            Question = "Soruları sadece belli öğrencilere mi, yoksa tüm sınıfa mı yöneltiyor?"
                        },
                        new
                        {
                            Id = new Guid("6bda2993-60e0-4dd4-9de7-256f6888659c"),
                            Category = "🙋 Öğrenci Katılımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Order = 23,
                            Question = "Öğrencilere düşünme zamanı (bekleme süresi) veriyor mu?"
                        },
                        new
                        {
                            Id = new Guid("f7b6fe72-3fba-407b-8f82-13f79f57f033"),
                            Category = "🙋 Öğrenci Katılımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Order = 24,
                            Question = "Öğrenci cevaplarını dinliyor mu, yoksa cevabı kendisi mi tamamlıyor?"
                        },
                        new
                        {
                            Id = new Guid("47368a71-c320-40c8-bf70-570c60f4b216"),
                            Category = "🙋 Öğrenci Katılımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Order = 25,
                            Question = "Öğrencilerin birbirini dinlemesini ve tartışmasını teşvik ediyor mu?"
                        },
                        new
                        {
                            Id = new Guid("9def99f6-992d-4c43-9db9-3640b3a779e5"),
                            Category = "🙋 Öğrenci Katılımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Order = 26,
                            Question = "Gönüllü olmayan öğrencileri derse nasıl dahil ediyor?"
                        },
                        new
                        {
                            Id = new Guid("f6f8efe1-a6ea-4f5f-9077-60e082150bd6"),
                            Category = "🙋 Öğrenci Katılımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Order = 27,
                            Question = "Grup çalışması ya da işbirlikli öğrenme var mı?"
                        },
                        new
                        {
                            Id = new Guid("ca8ec27f-74f6-4a6d-93c1-0278e1172217"),
                            Category = "🙋 Öğrenci Katılımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Order = 28,
                            Question = "Öğrencilerin kendi fikirlerini ifade etmelerine alan açıyor mu?"
                        },
                        new
                        {
                            Id = new Guid("01af916a-811f-4d0c-a6fe-4a73e323eab4"),
                            Category = "💬 Geri Bildirim & Soru-Cevap",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            Order = 29,
                            Question = "Öğrenci cevapları doğru olduğunda nasıl geri bildirim veriyor?"
                        },
                        new
                        {
                            Id = new Guid("87901df8-f1f5-49c5-9bca-c612d4954441"),
                            Category = "💬 Geri Bildirim & Soru-Cevap",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            Order = 30,
                            Question = "Yanlış cevaplarda öğrenciyi küçük düşürüyor mu, yoksa yapıcı mı yaklaşıyor?"
                        },
                        new
                        {
                            Id = new Guid("59b7aa4d-1886-4d54-a01a-b0a336905a6f"),
                            Category = "💬 Geri Bildirim & Soru-Cevap",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            Order = 31,
                            Question = "Öğrencinin sorusunu doğru anlayıp yanıtlıyor mu?"
                        },
                        new
                        {
                            Id = new Guid("db03de7c-da24-44f4-9fef-729784dfd348"),
                            Category = "💬 Geri Bildirim & Soru-Cevap",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            Order = 32,
                            Question = "Cevabı bilmeyen öğrenciye nasıl yaklaşıyor?"
                        },
                        new
                        {
                            Id = new Guid("602d5eec-bdc0-4424-81c6-0c7eb6bfce03"),
                            Category = "💬 Geri Bildirim & Soru-Cevap",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            Order = 33,
                            Question = "Geri bildirimler spesifik mi (\"aferin\" gibi genel mi, yoksa \"şunu iyi yaptın çünkü…\" gibi açıklayıcı mı)?"
                        },
                        new
                        {
                            Id = new Guid("b5e1e614-8859-41f0-be04-ddebd99c7788"),
                            Category = "💬 Geri Bildirim & Soru-Cevap",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            Order = 34,
                            Question = "Öğrencilerin anladığını nasıl kontrol ediyor — anlama soruları soruyor mu?"
                        },
                        new
                        {
                            Id = new Guid("96f9db6e-9ce1-44db-be34-783db04030e9"),
                            Category = "🏫 Sınıf Yönetimi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Order = 35,
                            Question = "Sınıfta genel düzen ve sessizlik sağlanabiliyor mu?"
                        },
                        new
                        {
                            Id = new Guid("8a8344ce-2554-4e72-b58f-56c4605dc03f"),
                            Category = "🏫 Sınıf Yönetimi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Order = 36,
                            Question = "Derse odaklanamayan ya da konuşan öğrencilerle nasıl başa çıkıyor?"
                        },
                        new
                        {
                            Id = new Guid("b97015c8-fbce-42e9-8418-2f8f418b8f0c"),
                            Category = "🏫 Sınıf Yönetimi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Order = 37,
                            Question = "Disiplin müdahalesi varsa nasıl yapılıyor — saygılı mı, agresif mi?"
                        },
                        new
                        {
                            Id = new Guid("4f65f304-19ca-47a6-9579-100d3df19278"),
                            Category = "🏫 Sınıf Yönetimi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Order = 38,
                            Question = "Zamanı iyi yönetiyor mu — ders planladığı gibi ilerliyor mu?"
                        },
                        new
                        {
                            Id = new Guid("de9281f6-4236-4945-8668-200e018a5c22"),
                            Category = "🏫 Sınıf Yönetimi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Order = 39,
                            Question = "Geçişler (yeni konuya geçiş, aktivite değişimi) pürüzsüz mü?"
                        },
                        new
                        {
                            Id = new Guid("fe897cfb-0d44-4a8b-a3ea-13d726639fd7"),
                            Category = "🏫 Sınıf Yönetimi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Order = 40,
                            Question = "Beklenmedik durumlara (teknik sorun, öğrenci sorusu, vs.) nasıl tepki veriyor?"
                        },
                        new
                        {
                            Id = new Guid("32f441db-6747-4803-b1dd-ba5f63158826"),
                            Category = "🖥️ Materyal & Araç Kullanımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000006"),
                            IsActive = true,
                            Order = 41,
                            Question = "Kullanılan materyaller (slayt, tahta, video, vs.) içerikle uyumlu ve kaliteli mi?"
                        },
                        new
                        {
                            Id = new Guid("0d7bd867-9b68-4629-86c6-9784282941d1"),
                            Category = "🖥️ Materyal & Araç Kullanımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000006"),
                            IsActive = true,
                            Order = 42,
                            Question = "Tahtayı/ekranı düzenli ve okunabilir şekilde mi kullanıyor?"
                        },
                        new
                        {
                            Id = new Guid("1a35ff6e-be2b-48f2-af81-b119d1c44edf"),
                            Category = "🖥️ Materyal & Araç Kullanımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000006"),
                            IsActive = true,
                            Order = 43,
                            Question = "Görsel materyaller öğrenmeyi destekliyor mu, yoksa dikkat dağıtıyor mu?"
                        },
                        new
                        {
                            Id = new Guid("9983723c-2f9e-49dc-9e05-49065822ad4d"),
                            Category = "🖥️ Materyal & Araç Kullanımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000006"),
                            IsActive = true,
                            Order = 44,
                            Question = "Teknolojiyi etkin mi kullanıyor?"
                        },
                        new
                        {
                            Id = new Guid("11a40eff-9df7-4d95-a4f1-c3f64e1d8551"),
                            Category = "🖥️ Materyal & Araç Kullanımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000006"),
                            IsActive = true,
                            Order = 45,
                            Question = "Materyaller tüm öğrencilerin görebileceği şekilde konumlandırılmış mı?"
                        },
                        new
                        {
                            Id = new Guid("25d673b4-908a-4ed2-bee3-53c3a6a63a40"),
                            Category = "👥 Öğrenci Davranışı & Sınıf Atmosferi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsActive = true,
                            Order = 46,
                            Question = "Öğrencilerin genel ilgi ve odaklanma düzeyi nasıl?"
                        },
                        new
                        {
                            Id = new Guid("16e7b4ef-cd0f-4d2f-94f1-23643e0b12ce"),
                            Category = "👥 Öğrenci Davranışı & Sınıf Atmosferi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsActive = true,
                            Order = 47,
                            Question = "Öğrenciler ders sırasında ne yapıyor — not mu alıyor, telefonla mı ilgileniyor, konuşuyor mu?"
                        },
                        new
                        {
                            Id = new Guid("5b251256-d40c-422a-a102-b82bd12b942f"),
                            Category = "👥 Öğrenci Davranışı & Sınıf Atmosferi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsActive = true,
                            Order = 48,
                            Question = "Öğrencilerin soru sorma ya da katılım istekliliği var mı?"
                        },
                        new
                        {
                            Id = new Guid("e57f0c79-538c-4f4a-9080-2985e96dcbd5"),
                            Category = "👥 Öğrenci Davranışı & Sınıf Atmosferi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsActive = true,
                            Order = 49,
                            Question = "Sınıfta pozitif, güvenli bir öğrenme ortamı var mı?"
                        },
                        new
                        {
                            Id = new Guid("1bee0fab-b412-4618-a6b1-d7ca89057d41"),
                            Category = "👥 Öğrenci Davranışı & Sınıf Atmosferi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsActive = true,
                            Order = 50,
                            Question = "Öğretmen-öğrenci ilişkisi nasıl görünüyor — saygılı, mesafeli, sıcak?"
                        },
                        new
                        {
                            Id = new Guid("cc029d08-218a-4657-a14c-7a946fb4545c"),
                            Category = "👥 Öğrenci Davranışı & Sınıf Atmosferi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsActive = true,
                            Order = 51,
                            Question = "Öğrencilerin yüz ifadeleri ve beden dili neler söylüyor — sıkılmış mı, meraklı mı?"
                        },
                        new
                        {
                            Id = new Guid("4514ceb1-2ec6-4577-a399-ccda4c433d23"),
                            Category = "👥 Öğrenci Davranışı & Sınıf Atmosferi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsActive = true,
                            Order = 52,
                            Question = "Dersin hangi anlarında öğrenci enerjisi yükseliyor ya da düşüyor?"
                        },
                        new
                        {
                            Id = new Guid("2c9ba458-2a3e-41f4-9aec-4c4e172023c7"),
                            Category = "🌍 Kapsayıcılık & Farklılaştırma",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000007"),
                            IsActive = true,
                            Order = 53,
                            Question = "Farklı öğrenme hızlarındaki öğrencilere uyum sağlıyor mu?"
                        },
                        new
                        {
                            Id = new Guid("a81f4e2c-3969-4b81-bcdb-a53d5a152d81"),
                            Category = "🌍 Kapsayıcılık & Farklılaştırma",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000007"),
                            IsActive = true,
                            Order = 54,
                            Question = "Öğrenme güçlüğü çeken öğrenciye özel ilgi gösteriyor mu?"
                        },
                        new
                        {
                            Id = new Guid("32de9310-1ad3-47cf-adef-956a8c720de8"),
                            Category = "🌍 Kapsayıcılık & Farklılaştırma",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000007"),
                            IsActive = true,
                            Order = 55,
                            Question = "Tüm öğrencilere eşit mesafede mi davranıyor, favoriler var mı?"
                        },
                        new
                        {
                            Id = new Guid("c9bb7337-e80a-4632-9d39-163118daf3a5"),
                            Category = "🔄 Genel Ders Değerlendirmesi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000010"),
                            IsActive = true,
                            Order = 56,
                            Question = "Bu dersi izleyen biri ne öğrendiğini açıklayabilir mi?"
                        },
                        new
                        {
                            Id = new Guid("92cf3727-c4c1-46b6-93de-c6ef48b0910f"),
                            Category = "🔄 Genel Ders Değerlendirmesi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000010"),
                            IsActive = true,
                            Order = 57,
                            Question = "Ders tekrar izlenmeli miydi, yoksa tek seferde anlaşılır mıydı?"
                        },
                        new
                        {
                            Id = new Guid("ac26de94-f436-4d35-b664-0e2e1e2dd28c"),
                            Category = "🔄 Genel Ders Değerlendirmesi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000010"),
                            IsActive = true,
                            Order = 58,
                            Question = "Öğretmenin en güçlü 3 yönü nedir?"
                        },
                        new
                        {
                            Id = new Guid("ea58925d-e473-4f98-9b66-6033f59d0836"),
                            Category = "🔄 Genel Ders Değerlendirmesi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000010"),
                            IsActive = true,
                            Order = 59,
                            Question = "Öğretmenin gelişim alanları nelerdir — somut önerilerle?"
                        },
                        new
                        {
                            Id = new Guid("ed1bb51e-be0c-43b1-a638-9bb6fa70989c"),
                            Category = "🔄 Genel Ders Değerlendirmesi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000010"),
                            IsActive = true,
                            Order = 60,
                            Question = "Bu ders için genel bir başarı puanı verilseydi ne olurdu (1-10)?"
                        },
                        new
                        {
                            Id = new Guid("af01fe96-aef4-4cd6-8fb8-2cd9ebc4176c"),
                            Category = "🔄 Genel Ders Değerlendirmesi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000010"),
                            IsActive = true,
                            Order = 61,
                            Question = "Bir sonraki derste öncelikli olarak iyileştirilmesi gereken tek şey ne?"
                        });
                });

            modelBuilder.Entity("Insyte.Core.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PdfPath")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("EvaluationId")
                        .IsUnique();

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Room")
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherUserId");

                    b.HasIndex("ClassId", "DayOfWeek", "StartTime");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Insyte.Core.Entities.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EducationSystem")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("InstitutionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LiseType")
                        .HasColumnType("text");

                    b.Property<string>("LogoPath")
                        .HasColumnType("text");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("SchoolType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "Activity")
                        .IsUnique();

                    b.ToTable("SchoolActivities");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolAdvisor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("SchoolId", "UserId")
                        .IsUnique();

                    b.ToTable("SchoolAdvisors");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolFacility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Facility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "Facility")
                        .IsUnique();

                    b.ToTable("SchoolFacilities");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "Language")
                        .IsUnique();

                    b.ToTable("SchoolLanguages");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolServiceOffering", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "Service")
                        .IsUnique();

                    b.ToTable("SchoolServices");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("SchoolId", "UserId")
                        .IsUnique();

                    b.ToTable("SchoolUsers");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WeeklyHours")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "Name");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Insyte.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@insyte.com",
                            FirstName = "System",
                            IsActive = true,
                            LastName = "Admin",
                            PasswordHash = "$2a$11$0BISi69986QCN8DQdYtLJ.q5KedTBUjt3rBNp2R8m26dsddJWhXii",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("Insyte.Core.Entities.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.Property<Guid>("TeacherUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("TeacherUserId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("Videos");
                });


            modelBuilder.Entity("Insyte.Core.Entities.AIModel", b =>
                {
                    b.HasOne("Insyte.Core.Entities.AIProvider", "AIProvider")
                        .WithMany("Models")
                        .HasForeignKey("AIProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AIProvider");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Class", b =>
                {
                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("Classes")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });


            modelBuilder.Entity("Insyte.Core.Entities.EmailConfig", b =>
                {
                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("EmailConfigs")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Insyte.Core.Entities.EmailLog", b =>
                {
                    b.HasOne("Insyte.Core.Entities.Report", "Report")
                        .WithMany("EmailLogs")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Evaluation", b =>
                {
                    b.HasOne("Insyte.Core.Entities.AIModel", "AIModel")
                        .WithMany("Evaluations")
                        .HasForeignKey("AIModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Insyte.Core.Entities.EvaluationCriteria", "Criteria")
                        .WithMany("Evaluations")
                        .HasForeignKey("CriteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Insyte.Core.Entities.Video", "Video")
                        .WithMany("Evaluations")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AIModel");

                    b.Navigation("Criteria");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Insyte.Core.Entities.EvaluationQuestion", b =>
                {
                    b.HasOne("Insyte.Core.Entities.EvaluationCriteria", "Criteria")
                        .WithMany("Questions")
                        .HasForeignKey("CriteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Report", b =>
                {
                    b.HasOne("Insyte.Core.Entities.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Insyte.Core.Entities.Evaluation", "Evaluation")
                        .WithOne("Report")
                        .HasForeignKey("Insyte.Core.Entities.Report", "EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Schedule", b =>
                {
                    b.HasOne("Insyte.Core.Entities.Class", "Class")
                        .WithMany("Schedules")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("Schedules")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Insyte.Core.Entities.Subject", "Subject")
                        .WithMany("Schedules")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Insyte.Core.Entities.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("School");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolActivity", b =>
                {
                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("Activities")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolAdvisor", b =>
                {
                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("Advisors")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Insyte.Core.Entities.User", "User")
                        .WithMany("AdvisedSchools")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolFacility", b =>
                {
                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("Facilities")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolLanguage", b =>
                {
                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("Languages")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolServiceOffering", b =>
                {
                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("Services")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolUser", b =>
                {
                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("Users")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Insyte.Core.Entities.User", "User")
                        .WithMany("SchoolUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Subject", b =>
                {
                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("Subjects")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Video", b =>
                {
                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("Videos")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Insyte.Core.Entities.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Insyte.Core.Entities.User", "UploadedBy")
                        .WithMany("UploadedVideos")
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("Teacher");

                    b.Navigation("UploadedBy");
                });


            modelBuilder.Entity("Insyte.Core.Entities.AIModel", b =>
                {
                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("Insyte.Core.Entities.AIProvider", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Class", b =>
                {
                    b.Navigation("Schedules");
                });


            modelBuilder.Entity("Insyte.Core.Entities.Evaluation", b =>
                {
                    b.Navigation("Report");
                });

            modelBuilder.Entity("Insyte.Core.Entities.EvaluationCriteria", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Report", b =>
                {
                    b.Navigation("EmailLogs");
                });

            modelBuilder.Entity("Insyte.Core.Entities.School", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Advisors");

                    b.Navigation("Classes");

                    b.Navigation("EmailConfigs");

                    b.Navigation("Facilities");

                    b.Navigation("Languages");

                    b.Navigation("Schedules");

                    b.Navigation("Services");

                    b.Navigation("Subjects");

                    b.Navigation("Users");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Subject", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Insyte.Core.Entities.User", b =>
                {
                    b.Navigation("AdvisedSchools");

                    b.Navigation("SchoolUsers");

                    b.Navigation("UploadedVideos");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Video", b =>
                {
                    b.Navigation("Evaluations");
                });

#pragma warning restore 612, 618
        }
    }
}
