// <auto-generated />
using System;
using Insyte.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Insyte.Infrastructure.Migrations
{
    [DbContext(typeof(InsyteDbContext))]
    partial class InsyteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Insyte.Core.Entities.AIModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AIProviderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxTokens")
                        .HasColumnType("integer");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AIProviderId");

                    b.ToTable("AIModels");
                });

            modelBuilder.Entity("Insyte.Core.Entities.AIProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .HasColumnType("text");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AIProviders");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "Name");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Insyte.Core.Entities.EmailConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecipientName")
                        .HasColumnType("text");

                    b.Property<string>("RecipientType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("EmailConfigs");
                });

            modelBuilder.Entity("Insyte.Core.Entities.EmailLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("EmailLogs");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Evaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AIModelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CriteriaId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("Result")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TokenUsageInput")
                        .HasColumnType("integer");

                    b.Property<int>("TokenUsageOutput")
                        .HasColumnType("integer");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AIModelId");

                    b.HasIndex("CriteriaId");

                    b.HasIndex("VideoId");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("Insyte.Core.Entities.EvaluationCriteria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("EvaluationCriteria");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dersin yapısı, hedef belirleme, müfredatla uyum, konuyu doğru aktarma",
                            Instructions = "Öğretmenin ders planını oluşturma, hedefler belirleme ve müfredata uygun içerik sunma becerisini değerlendirin.",
                            IsActive = true,
                            Name = "Pedagojik Yeterlilik"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ses tonu, konuşma hızı, beden dili, göz teması, dil kullanımı",
                            Instructions = "Öğretmenin iletişim stilini, konuşma netliğini, beden dilini ve sınıf içinde etkileşim kurma becerilerini değerlendirin.",
                            IsActive = true,
                            Name = "İletişim & Sunum Becerileri"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Öğrencileri derse dahil etme, sorular sorma, ilgiyi canlı tutma",
                            Instructions = "Öğrencilerin derse katılım düzeyini, motivasyon seviyesini ve öğretmenin etkileşim kurma çabalarını değerlendirin.",
                            IsActive = true,
                            Name = "Öğrenci Katılımı & Motivasyonu"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Düzeni sağlama, zaman yönetimi, disiplin yaklaşımı",
                            Instructions = "Sınıf düzeninin sağlanması, zamanın etkili kullanılması ve disiplin yaklaşımının uygunluğunu değerlendirin.",
                            IsActive = true,
                            Name = "Sınıf Yönetimi"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Öğrenci sorularını yanıtlama, anlık geri bildirim, yönlendirme",
                            Instructions = "Öğrenci sorularına verilen cevapların kalitesini, geri bildirim etkinliğini ve yapıcı yönlendirmeyi değerlendirin.",
                            IsActive = true,
                            Name = "Soru-Cevap & Geri Bildirim Kalitesi"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tahta, slayt, araç-gereç kullanımı, materyallerin etkinliği",
                            Instructions = "Öğretim materyallerinin uygunluğunu, çeşitliliğini ve etkili kullanımını değerlendirin.",
                            IsActive = true,
                            Name = "Materyal & Görsel Kullanımı"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Farklı öğrenme düzeylerine hitap etme, bireysel ilgi",
                            Instructions = "Öğretmenin farklı öğrenme stillerine ve seviyelere uygun öğretim stratejileri kullanıp kullanmadığını değerlendirin.",
                            IsActive = true,
                            Name = "Farklılaştırılmış Öğretim"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Öğrencilerin ilgi düzeyi, katılım, beden dili, motivasyon",
                            Instructions = "Öğrencilerin derste gösterdikleri ilgi, katılım düzeyi, beden dilini ve genel motivasyon durumunu değerlendirin.",
                            IsActive = true,
                            Name = "Öğrenci Davranışı & Tepkileri"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Konuyu doğru ve anlaşılır aktarma, yanlış bilgi var mı",
                            Instructions = "Öğretmenin konuyu doğru bir şekilde anlatan, yanlış bilgi içermeyen ve anlaşılır bir dil kullanıp kullanmadığını değerlendirin.",
                            IsActive = true,
                            Name = "Dil & Kavram Doğruluğu"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Başlangıç-orta-kapanış dengesi, geçişler, süre yönetimi",
                            Instructions = "Dersin başlangıcından sonuna kadar akışını, geçişlerin uygunluğunu ve zamanın dengeli kullanılıp kullanılmadığını değerlendirin.",
                            IsActive = true,
                            Name = "Genel Ders Akışı & Tempo"
                        });
                });

            modelBuilder.Entity("Insyte.Core.Entities.EvaluationQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CriteriaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CriteriaId", "Order");

                    b.ToTable("EvaluationQuestions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("500c595d-033a-4519-a5a0-757fc6a715ca"),
                            Category = "🗣️ İletişim & Ses",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 1,
                            Question = "Öğretmenin sesi net ve anlaşılır mı, yoksa çok alçak/yüksek mi konuşuyor?"
                        },
                        new
                        {
                            Id = new Guid("f472b428-591f-4d18-8610-b1a1b2ba8806"),
                            Category = "🗣️ İletişim & Ses",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 2,
                            Question = "Konuşma hızı uygun mu — çok hızlı veya çok yavaş mı?"
                        },
                        new
                        {
                            Id = new Guid("a2d88610-d48c-433e-8624-2794730ce4a4"),
                            Category = "🗣️ İletişim & Ses",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 3,
                            Question = "Öğretmen monoton mu konuşuyor, yoksa ses tonunda çeşitlilik var mı?"
                        },
                        new
                        {
                            Id = new Guid("fdcabcbf-5099-4e8f-94f5-3f12beef9293"),
                            Category = "🗣️ İletişim & Ses",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 4,
                            Question = "Önemli kavramları vurgularken ses tonunu değiştiriyor mu?"
                        },
                        new
                        {
                            Id = new Guid("0f42af9b-cff7-4d7b-8b71-c2ad4811dabd"),
                            Category = "🗣️ İletişim & Ses",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 5,
                            Question = "Türkçeyi (ya da ders dilini) doğru ve akıcı kullanıyor mu?"
                        },
                        new
                        {
                            Id = new Guid("fdd43b83-451b-41a2-84bc-07384f7a02e3"),
                            Category = "🗣️ İletişim & Ses",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 6,
                            Question = "Gereksiz dolgu sözler (yani, şey, hmm) ne sıklıkla kullanılıyor?"
                        },
                        new
                        {
                            Id = new Guid("9d9fc366-ed57-4e85-a563-7aa4d8e3dc11"),
                            Category = "🗣️ İletişim & Ses",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 7,
                            Question = "Öğrencilere hitap ederken ne kadar samimi ve sıcak bir ton kullanıyor?"
                        },
                        new
                        {
                            Id = new Guid("702aa571-bf16-44c8-bdd7-1340611a5781"),
                            Category = "🧍 Beden Dili & Fiziksel Varlık",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 8,
                            Question = "Öğretmen sınıfı aktif olarak dolaşıyor mu, yoksa tek noktada mı duruyor?"
                        },
                        new
                        {
                            Id = new Guid("acc3fbc4-9876-43d6-8e95-ac163b06e8b0"),
                            Category = "🧍 Beden Dili & Fiziksel Varlık",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 9,
                            Question = "Göz teması kuruyor mu — sadece tahtaya mı bakıyor, öğrencilere mi?"
                        },
                        new
                        {
                            Id = new Guid("7de43be5-fa86-4566-9acf-5a8d3f3b7038"),
                            Category = "🧍 Beden Dili & Fiziksel Varlık",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 10,
                            Question = "El, kol hareketleri anlatımı destekliyor mu?"
                        },
                        new
                        {
                            Id = new Guid("bc3efa96-3b8b-45a6-8f84-1d0e0c2e49a4"),
                            Category = "🧍 Beden Dili & Fiziksel Varlık",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 11,
                            Question = "Öğrencilere karşı açık ve davetkar bir duruş mu sergiliyor?"
                        },
                        new
                        {
                            Id = new Guid("c02603d4-5620-40dc-97a1-9861d9dd818e"),
                            Category = "🧍 Beden Dili & Fiziksel Varlık",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Order = 12,
                            Question = "Yüz ifadeleri anlatılanlarla uyumlu mu?"
                        },
                        new
                        {
                            Id = new Guid("2709dd27-84b9-4163-952e-b6f8664097b4"),
                            Category = "📚 Pedagoji & Ders İçeriği",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Order = 13,
                            Question = "Dersin başında öğrencilere neyi öğreneceklerini açıklıyor mu?"
                        },
                        new
                        {
                            Id = new Guid("d4071b27-401d-4673-8188-8a9ec015adf7"),
                            Category = "📚 Pedagoji & Ders İçeriği",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Order = 14,
                            Question = "Konu anlatımı mantıksal bir sırayla ilerliyor mu?"
                        },
                        new
                        {
                            Id = new Guid("70d4c1de-a375-477d-9fc8-93b383a22130"),
                            Category = "📚 Pedagoji & Ders İçeriği",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Order = 15,
                            Question = "Öğrettiği bilgiler doğru mu — kavram veya bilgi hatası var mı?"
                        },
                        new
                        {
                            Id = new Guid("7e1060d6-afa6-49a9-854f-e7cab2aa6e17"),
                            Category = "📚 Pedagoji & Ders İçeriği",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Order = 16,
                            Question = "Konuyu günlük hayatla ilişkilendiriyor mu, somut örnekler veriyor mu?"
                        },
                        new
                        {
                            Id = new Guid("654df319-08b2-43bb-a4a8-9b74bf55748c"),
                            Category = "📚 Pedagoji & Ders İçeriği",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Order = 17,
                            Question = "Karmaşık kavramları basitten karmaşığa doğru açıklıyor mu?"
                        },
                        new
                        {
                            Id = new Guid("fa59e0b4-46c8-49ef-a5f1-59b0e8b97477"),
                            Category = "📚 Pedagoji & Ders İçeriği",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Order = 18,
                            Question = "Önceki derslerle bağlantı kuruyor mu?"
                        },
                        new
                        {
                            Id = new Guid("35de297e-465d-4213-9ca7-56d7e14f2e7d"),
                            Category = "📚 Pedagoji & Ders İçeriği",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Order = 19,
                            Question = "Ders sonunda özet ya da tekrar yapıyor mu?"
                        },
                        new
                        {
                            Id = new Guid("c305bd6e-b1d8-484d-a13d-e54b37857bbe"),
                            Category = "📚 Pedagoji & Ders İçeriği",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Order = 20,
                            Question = "Ders hedefine ulaşıldı mı — dersin sonunda öğrenciler konuyu anlamış görünüyor mu?"
                        },
                        new
                        {
                            Id = new Guid("9039a6bc-c359-457c-8bf7-30c10c439aec"),
                            Category = "🙋 Öğrenci Katılımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Order = 21,
                            Question = "Öğrencilere ne sıklıkla soru soruyor?"
                        },
                        new
                        {
                            Id = new Guid("6ebde72c-1d11-4121-8ff1-da8f6e8a157e"),
                            Category = "🙋 Öğrenci Katılımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Order = 22,
                            Question = "Soruları sadece belli öğrencilere mi, yoksa tüm sınıfa mı yöneltiyor?"
                        },
                        new
                        {
                            Id = new Guid("210ac981-4f3a-4080-9039-b51887a415ee"),
                            Category = "🙋 Öğrenci Katılımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Order = 23,
                            Question = "Öğrencilere düşünme zamanı (bekleme süresi) veriyor mu?"
                        },
                        new
                        {
                            Id = new Guid("c1860b06-5f17-4e4a-9d2a-c526be59321d"),
                            Category = "🙋 Öğrenci Katılımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Order = 24,
                            Question = "Öğrenci cevaplarını dinliyor mu, yoksa cevabı kendisi mi tamamlıyor?"
                        },
                        new
                        {
                            Id = new Guid("cdc2d783-0720-4d46-843e-8c70bbda07a6"),
                            Category = "🙋 Öğrenci Katılımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Order = 25,
                            Question = "Öğrencilerin birbirini dinlemesini ve tartışmasını teşvik ediyor mu?"
                        },
                        new
                        {
                            Id = new Guid("1955ef00-24b4-4052-977a-06354d397080"),
                            Category = "🙋 Öğrenci Katılımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Order = 26,
                            Question = "Gönüllü olmayan öğrencileri derse nasıl dahil ediyor?"
                        },
                        new
                        {
                            Id = new Guid("4edf6f71-c5c7-4c85-b2f1-44f0e7e13064"),
                            Category = "🙋 Öğrenci Katılımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Order = 27,
                            Question = "Grup çalışması ya da işbirlikli öğrenme var mı?"
                        },
                        new
                        {
                            Id = new Guid("ada828cb-33d1-418b-be1b-abe3193daed0"),
                            Category = "🙋 Öğrenci Katılımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Order = 28,
                            Question = "Öğrencilerin kendi fikirlerini ifade etmelerine alan açıyor mu?"
                        },
                        new
                        {
                            Id = new Guid("6a9d92db-0897-4058-b656-85d54fc99786"),
                            Category = "💬 Geri Bildirim & Soru-Cevap",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            Order = 29,
                            Question = "Öğrenci cevapları doğru olduğunda nasıl geri bildirim veriyor?"
                        },
                        new
                        {
                            Id = new Guid("07a4b017-7e8c-4fe4-b418-a41207593b67"),
                            Category = "💬 Geri Bildirim & Soru-Cevap",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            Order = 30,
                            Question = "Yanlış cevaplarda öğrenciyi küçük düşürüyor mu, yoksa yapıcı mı yaklaşıyor?"
                        },
                        new
                        {
                            Id = new Guid("a2caf354-4ba6-42c9-912b-5b3567e99244"),
                            Category = "💬 Geri Bildirim & Soru-Cevap",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            Order = 31,
                            Question = "Öğrencinin sorusunu doğru anlayıp yanıtlıyor mu?"
                        },
                        new
                        {
                            Id = new Guid("2fe233bf-1201-4883-982a-e50723136acf"),
                            Category = "💬 Geri Bildirim & Soru-Cevap",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            Order = 32,
                            Question = "Cevabı bilmeyen öğrenciye nasıl yaklaşıyor?"
                        },
                        new
                        {
                            Id = new Guid("9cf4e3c0-c5f8-4c8a-a42c-d22b02662e70"),
                            Category = "💬 Geri Bildirim & Soru-Cevap",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            Order = 33,
                            Question = "Geri bildirimler spesifik mi (\"aferin\" gibi genel mi, yoksa \"şunu iyi yaptın çünkü…\" gibi açıklayıcı mı)?"
                        },
                        new
                        {
                            Id = new Guid("05ce08dd-3203-4e95-97fc-a9da1fb0dc9d"),
                            Category = "💬 Geri Bildirim & Soru-Cevap",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            Order = 34,
                            Question = "Öğrencilerin anladığını nasıl kontrol ediyor — anlama soruları soruyor mu?"
                        },
                        new
                        {
                            Id = new Guid("ad51468b-4e61-4e48-8708-70aad58f10a6"),
                            Category = "🏫 Sınıf Yönetimi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Order = 35,
                            Question = "Sınıfta genel düzen ve sessizlik sağlanabiliyor mu?"
                        },
                        new
                        {
                            Id = new Guid("17396e2c-000a-4cc8-926f-a825477a5ab7"),
                            Category = "🏫 Sınıf Yönetimi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Order = 36,
                            Question = "Derse odaklanamayan ya da konuşan öğrencilerle nasıl başa çıkıyor?"
                        },
                        new
                        {
                            Id = new Guid("76b7378f-a4e6-4aa2-90f5-b46cdd9e5b50"),
                            Category = "🏫 Sınıf Yönetimi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Order = 37,
                            Question = "Disiplin müdahalesi varsa nasıl yapılıyor — saygılı mı, agresif mi?"
                        },
                        new
                        {
                            Id = new Guid("ad138edb-3a0f-4bc4-836f-82817aa41b4e"),
                            Category = "🏫 Sınıf Yönetimi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Order = 38,
                            Question = "Zamanı iyi yönetiyor mu — ders planladığı gibi ilerliyor mu?"
                        },
                        new
                        {
                            Id = new Guid("114c018c-3c53-4ec5-82be-29843d01de63"),
                            Category = "🏫 Sınıf Yönetimi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Order = 39,
                            Question = "Geçişler (yeni konuya geçiş, aktivite değişimi) pürüzsüz mü?"
                        },
                        new
                        {
                            Id = new Guid("3eabb661-a029-468f-af1e-51552f4422e3"),
                            Category = "🏫 Sınıf Yönetimi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Order = 40,
                            Question = "Beklenmedik durumlara (teknik sorun, öğrenci sorusu, vs.) nasıl tepki veriyor?"
                        },
                        new
                        {
                            Id = new Guid("42bd976c-8abf-42ab-b901-e15d8d839036"),
                            Category = "🖥️ Materyal & Araç Kullanımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000006"),
                            IsActive = true,
                            Order = 41,
                            Question = "Kullanılan materyaller (slayt, tahta, video, vs.) içerikle uyumlu ve kaliteli mi?"
                        },
                        new
                        {
                            Id = new Guid("71d68ea9-5d32-444c-a600-b9a36985a3b5"),
                            Category = "🖥️ Materyal & Araç Kullanımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000006"),
                            IsActive = true,
                            Order = 42,
                            Question = "Tahtayı/ekranı düzenli ve okunabilir şekilde mi kullanıyor?"
                        },
                        new
                        {
                            Id = new Guid("cb706098-8eed-43d8-a3a4-d1436072cfb9"),
                            Category = "🖥️ Materyal & Araç Kullanımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000006"),
                            IsActive = true,
                            Order = 43,
                            Question = "Görsel materyaller öğrenmeyi destekliyor mu, yoksa dikkat dağıtıyor mu?"
                        },
                        new
                        {
                            Id = new Guid("8c9ce5cc-c5fe-4d8f-9b93-37c96f34ef4b"),
                            Category = "🖥️ Materyal & Araç Kullanımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000006"),
                            IsActive = true,
                            Order = 44,
                            Question = "Teknolojiyi etkin mi kullanıyor?"
                        },
                        new
                        {
                            Id = new Guid("79d0e1bd-6a64-4ff0-aff4-d9f9bab68416"),
                            Category = "🖥️ Materyal & Araç Kullanımı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000006"),
                            IsActive = true,
                            Order = 45,
                            Question = "Materyaller tüm öğrencilerin görebileceği şekilde konumlandırılmış mı?"
                        },
                        new
                        {
                            Id = new Guid("5f28d1a7-9fb6-4f0d-bc61-98990fd66c97"),
                            Category = "👥 Öğrenci Davranışı & Sınıf Atmosferi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsActive = true,
                            Order = 46,
                            Question = "Öğrencilerin genel ilgi ve odaklanma düzeyi nasıl?"
                        },
                        new
                        {
                            Id = new Guid("3b7b2de9-a9ca-4028-b63e-e53f6ac3b974"),
                            Category = "👥 Öğrenci Davranışı & Sınıf Atmosferi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsActive = true,
                            Order = 47,
                            Question = "Öğrenciler ders sırasında ne yapıyor — not mu alıyor, telefonla mı ilgileniyor, konuşuyor mu?"
                        },
                        new
                        {
                            Id = new Guid("76635c4d-a48d-42f0-9f31-3ebdcf2710d3"),
                            Category = "👥 Öğrenci Davranışı & Sınıf Atmosferi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsActive = true,
                            Order = 48,
                            Question = "Öğrencilerin soru sorma ya da katılım istekliliği var mı?"
                        },
                        new
                        {
                            Id = new Guid("4ebcdb3b-9707-4b9a-9426-2c4ac8307f3b"),
                            Category = "👥 Öğrenci Davranışı & Sınıf Atmosferi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsActive = true,
                            Order = 49,
                            Question = "Sınıfta pozitif, güvenli bir öğrenme ortamı var mı?"
                        },
                        new
                        {
                            Id = new Guid("d5e1f0ac-8b51-4853-81e8-3f8d394a4559"),
                            Category = "👥 Öğrenci Davranışı & Sınıf Atmosferi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsActive = true,
                            Order = 50,
                            Question = "Öğretmen-öğrenci ilişkisi nasıl görünüyor — saygılı, mesafeli, sıcak?"
                        },
                        new
                        {
                            Id = new Guid("2718cb4a-84ad-4103-a324-562d3f934df4"),
                            Category = "👥 Öğrenci Davranışı & Sınıf Atmosferi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsActive = true,
                            Order = 51,
                            Question = "Öğrencilerin yüz ifadeleri ve beden dili neler söylüyor — sıkılmış mı, meraklı mı?"
                        },
                        new
                        {
                            Id = new Guid("223ef81e-f374-475f-89ac-83d04cca2ad2"),
                            Category = "👥 Öğrenci Davranışı & Sınıf Atmosferi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsActive = true,
                            Order = 52,
                            Question = "Dersin hangi anlarında öğrenci enerjisi yükseliyor ya da düşüyor?"
                        },
                        new
                        {
                            Id = new Guid("fe1c9003-7923-4770-add8-3966bb61f942"),
                            Category = "🌍 Kapsayıcılık & Farklılaştırma",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000007"),
                            IsActive = true,
                            Order = 53,
                            Question = "Farklı öğrenme hızlarındaki öğrencilere uyum sağlıyor mu?"
                        },
                        new
                        {
                            Id = new Guid("014e083a-9c33-4cd6-82cc-3137fd185846"),
                            Category = "🌍 Kapsayıcılık & Farklılaştırma",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000007"),
                            IsActive = true,
                            Order = 54,
                            Question = "Öğrenme güçlüğü çeken öğrenciye özel ilgi gösteriyor mu?"
                        },
                        new
                        {
                            Id = new Guid("2055e96c-4865-45d1-b5bc-77a5159bcb52"),
                            Category = "🌍 Kapsayıcılık & Farklılaştırma",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000007"),
                            IsActive = true,
                            Order = 55,
                            Question = "Tüm öğrencilere eşit mesafede mi davranıyor, favoriler var mı?"
                        },
                        new
                        {
                            Id = new Guid("f678e27b-7032-4730-8617-1345698011e2"),
                            Category = "🔄 Genel Ders Değerlendirmesi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000010"),
                            IsActive = true,
                            Order = 56,
                            Question = "Bu dersi izleyen biri ne öğrendiğini açıklayabilir mi?"
                        },
                        new
                        {
                            Id = new Guid("01098f9e-566d-42c4-9ad7-c43c30c1d253"),
                            Category = "🔄 Genel Ders Değerlendirmesi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000010"),
                            IsActive = true,
                            Order = 57,
                            Question = "Ders tekrar izlenmeli miydi, yoksa tek seferde anlaşılır mıydı?"
                        },
                        new
                        {
                            Id = new Guid("08381de1-ed3f-4d45-acfa-ae57fea26105"),
                            Category = "🔄 Genel Ders Değerlendirmesi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000010"),
                            IsActive = true,
                            Order = 58,
                            Question = "Öğretmenin en güçlü 3 yönü nedir?"
                        },
                        new
                        {
                            Id = new Guid("626955c6-6eb1-42c3-905c-77cff0c66f4d"),
                            Category = "🔄 Genel Ders Değerlendirmesi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000010"),
                            IsActive = true,
                            Order = 59,
                            Question = "Öğretmenin gelişim alanları nelerdir — somut önerilerle?"
                        },
                        new
                        {
                            Id = new Guid("023c1dcf-a407-4a12-a665-093366a7df07"),
                            Category = "🔄 Genel Ders Değerlendirmesi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000010"),
                            IsActive = true,
                            Order = 60,
                            Question = "Bu ders için genel bir başarı puanı verilseydi ne olurdu (1-10)?"
                        },
                        new
                        {
                            Id = new Guid("3c1d1e9a-4a66-4bc2-9487-39b4e63d4c72"),
                            Category = "🔄 Genel Ders Değerlendirmesi",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriteriaId = new Guid("10000000-0000-0000-0000-000000000010"),
                            IsActive = true,
                            Order = 61,
                            Question = "Bir sonraki derste öncelikli olarak iyileştirilmesi gereken tek şey ne?"
                        });
                });

            modelBuilder.Entity("Insyte.Core.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PdfPath")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("EvaluationId")
                        .IsUnique();

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Room")
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherUserId");

                    b.HasIndex("ClassId", "DayOfWeek", "StartTime");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Insyte.Core.Entities.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EducationSystem")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("InstitutionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LiseType")
                        .HasColumnType("text");

                    b.Property<string>("LogoPath")
                        .HasColumnType("text");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("SchoolType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Address = "Mimar Sinan Cad. No:45",
                            City = "İstanbul",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "info@ataturk.edu.tr",
                            InstitutionType = "Devlet",
                            IsActive = true,
                            Name = "Atatürk Ortaokulu",
                            Phone = "0212 555 1234",
                            SchoolType = "Ortaokul",
                            Website = "www.ataturk.edu.tr"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Address = "Nispetiye Cad. No:123",
                            City = "İstanbul",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            EducationSystem = "MEBOdakliEgitim",
                            Email = "info@dostlisesi.edu.tr",
                            InstitutionType = "Ozel",
                            IsActive = true,
                            LiseType = "AnadoluLisesi",
                            Name = "Özel Dost Lisesi",
                            Phone = "0212 555 5678",
                            SchoolType = "Lise",
                            Website = "www.dostlisesi.edu.tr"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Address = "Ulus Mah. Atatürk Bulv. No:78",
                            City = "Ankara",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "info@biltek.edu.tr",
                            InstitutionType = "Devlet",
                            IsActive = true,
                            Name = "Bilim ve Teknoloji İlkokulu",
                            Phone = "0312 555 9012",
                            SchoolType = "Ilkokul",
                            Website = "www.biltek.edu.tr"
                        });
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "Activity")
                        .IsUnique();

                    b.ToTable("SchoolActivities");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolAdvisor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("SchoolId", "UserId")
                        .IsUnique();

                    b.ToTable("SchoolAdvisors");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolFacility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Facility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "Facility")
                        .IsUnique();

                    b.ToTable("SchoolFacilities");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "Language")
                        .IsUnique();

                    b.ToTable("SchoolLanguages");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolServiceOffering", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "Service")
                        .IsUnique();

                    b.ToTable("SchoolServices");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("SchoolId", "UserId")
                        .IsUnique();

                    b.ToTable("SchoolUsers");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WeeklyHours")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "Name");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fe331669-b544-4308-af83-6e30a7ec78ac"),
                            Branch = "Türkçe",
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Türkçe dilini ve edebiyatını öğretme",
                            IsActive = true,
                            Level = "6-7",
                            Name = "Türkçe",
                            SchoolId = new Guid("20000000-0000-0000-0000-000000000001"),
                            WeeklyHours = 4
                        },
                        new
                        {
                            Id = new Guid("6e132f98-c039-4b4a-a810-c0388fb2c4d8"),
                            Branch = "Matematik",
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Matematik öğretimi",
                            IsActive = true,
                            Level = "6-7",
                            Name = "Matematik",
                            SchoolId = new Guid("20000000-0000-0000-0000-000000000001"),
                            WeeklyHours = 4
                        },
                        new
                        {
                            Id = new Guid("0eb7bb23-9b37-473b-b219-b864ff6519f1"),
                            Branch = "İngilizce",
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "İngilizce dil öğretimi",
                            IsActive = true,
                            Level = "6-7",
                            Name = "İngilizce",
                            SchoolId = new Guid("20000000-0000-0000-0000-000000000001"),
                            WeeklyHours = 3
                        },
                        new
                        {
                            Id = new Guid("732f49c4-9337-469e-8189-ae84a8a56e68"),
                            Branch = "Fen",
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fen ve teknoloji öğretimi",
                            IsActive = true,
                            Level = "6-7",
                            Name = "Fen Bilgisi",
                            SchoolId = new Guid("20000000-0000-0000-0000-000000000001"),
                            WeeklyHours = 3
                        },
                        new
                        {
                            Id = new Guid("a2b33f05-ccc1-4559-938a-451d03091b3b"),
                            Branch = "Türkçe",
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Türkçe dilini ve edebiyatını öğretme",
                            IsActive = true,
                            Level = "10",
                            Name = "Türkçe",
                            SchoolId = new Guid("20000000-0000-0000-0000-000000000002"),
                            WeeklyHours = 3
                        },
                        new
                        {
                            Id = new Guid("e59da1f4-acf1-47fb-b49e-a94faf803c07"),
                            Branch = "Matematik",
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Matematik öğretimi",
                            IsActive = true,
                            Level = "10",
                            Name = "Matematik",
                            SchoolId = new Guid("20000000-0000-0000-0000-000000000002"),
                            WeeklyHours = 4
                        },
                        new
                        {
                            Id = new Guid("9c660cb8-be82-4a60-a8d6-e6458e9853b4"),
                            Branch = "Fen",
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fizik öğretimi",
                            IsActive = true,
                            Level = "10",
                            Name = "Fizik",
                            SchoolId = new Guid("20000000-0000-0000-0000-000000000002"),
                            WeeklyHours = 3
                        },
                        new
                        {
                            Id = new Guid("e059ab8c-d18a-4180-ad38-fcd2a49e3e58"),
                            Branch = "İngilizce",
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "İngilizce dil öğretimi",
                            IsActive = true,
                            Level = "10",
                            Name = "İngilizce",
                            SchoolId = new Guid("20000000-0000-0000-0000-000000000002"),
                            WeeklyHours = 3
                        },
                        new
                        {
                            Id = new Guid("8ff5e5f2-8b16-4fcd-a09c-a2e88621b935"),
                            Branch = "Türkçe",
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Türkçe dilini ve edebiyatını öğretme",
                            IsActive = true,
                            Level = "3",
                            Name = "Türkçe",
                            SchoolId = new Guid("20000000-0000-0000-0000-000000000003"),
                            WeeklyHours = 5
                        },
                        new
                        {
                            Id = new Guid("2522d2b6-efce-4ebf-85ff-058abace2099"),
                            Branch = "Matematik",
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Matematik öğretimi",
                            IsActive = true,
                            Level = "3",
                            Name = "Matematik",
                            SchoolId = new Guid("20000000-0000-0000-0000-000000000003"),
                            WeeklyHours = 5
                        });
                });

            modelBuilder.Entity("Insyte.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@insyte.com",
                            FirstName = "System",
                            IsActive = true,
                            LastName = "Admin",
                            PasswordHash = "$2a$11$5a8W62bzMqef/Qrg.e30k.z.MhNfs3zx5nKq89nYzyZd6ssXzKOi.",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ayse.yilmaz@school.edu.tr",
                            FirstName = "Ayşe",
                            IsActive = true,
                            LastName = "Yılmaz",
                            PasswordHash = "$2a$11$GKkJX06RZWApsb6H4UESBeNdRYjYLdKFnTa1zlJ0aVwQyPqzQ8IWu",
                            Role = "Teacher"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mehmet.kaya@school.edu.tr",
                            FirstName = "Mehmet",
                            IsActive = true,
                            LastName = "Kaya",
                            PasswordHash = "$2a$11$mDjpMxxAir825XCbGrRJe.o2K8P3pZUpymTlMfllQHvo2WhLD4k1S",
                            Role = "Teacher"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "fatih.demir@school.edu.tr",
                            FirstName = "Fatih",
                            IsActive = true,
                            LastName = "Demir",
                            PasswordHash = "$2a$11$R1XYbZuOrwbZFEWEkkAD1.P3tHnqUKC/.H7H9D4UkRqqxOuSWbp66",
                            Role = "Teacher"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sule.can@school.edu.tr",
                            FirstName = "Şule",
                            IsActive = true,
                            LastName = "Can",
                            PasswordHash = "$2a$11$boxOlkDhvni81V9j2LTZx.e4bHOAmFsrqeE1lD5V2ujgMfE4gMUIa",
                            Role = "Teacher"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ali.ozturk@school.edu.tr",
                            FirstName = "Ali",
                            IsActive = true,
                            LastName = "Öztürk",
                            PasswordHash = "$2a$11$ZN6lgGS/s/2Ho839TU.Ye.0pF22krR9.12NMVQjITHk4/mTjZEwqK",
                            Role = "Teacher"
                        });
                });

            modelBuilder.Entity("Insyte.Core.Entities.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.Property<Guid>("TeacherUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("TeacherUserId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("Insyte.Core.Entities.AIModel", b =>
                {
                    b.HasOne("Insyte.Core.Entities.AIProvider", "AIProvider")
                        .WithMany("Models")
                        .HasForeignKey("AIProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AIProvider");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Class", b =>
                {
                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("Classes")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Insyte.Core.Entities.EmailConfig", b =>
                {
                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("EmailConfigs")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Insyte.Core.Entities.EmailLog", b =>
                {
                    b.HasOne("Insyte.Core.Entities.Report", "Report")
                        .WithMany("EmailLogs")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Evaluation", b =>
                {
                    b.HasOne("Insyte.Core.Entities.AIModel", "AIModel")
                        .WithMany("Evaluations")
                        .HasForeignKey("AIModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Insyte.Core.Entities.EvaluationCriteria", "Criteria")
                        .WithMany("Evaluations")
                        .HasForeignKey("CriteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Insyte.Core.Entities.Video", "Video")
                        .WithMany("Evaluations")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AIModel");

                    b.Navigation("Criteria");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Insyte.Core.Entities.EvaluationQuestion", b =>
                {
                    b.HasOne("Insyte.Core.Entities.EvaluationCriteria", "Criteria")
                        .WithMany("Questions")
                        .HasForeignKey("CriteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Report", b =>
                {
                    b.HasOne("Insyte.Core.Entities.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Insyte.Core.Entities.Evaluation", "Evaluation")
                        .WithOne("Report")
                        .HasForeignKey("Insyte.Core.Entities.Report", "EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Schedule", b =>
                {
                    b.HasOne("Insyte.Core.Entities.Class", "Class")
                        .WithMany("Schedules")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("Schedules")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Insyte.Core.Entities.Subject", "Subject")
                        .WithMany("Schedules")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Insyte.Core.Entities.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("School");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolActivity", b =>
                {
                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("Activities")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolAdvisor", b =>
                {
                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("Advisors")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Insyte.Core.Entities.User", "User")
                        .WithMany("AdvisedSchools")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolFacility", b =>
                {
                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("Facilities")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolLanguage", b =>
                {
                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("Languages")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolServiceOffering", b =>
                {
                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("Services")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Insyte.Core.Entities.SchoolUser", b =>
                {
                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("Users")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Insyte.Core.Entities.User", "User")
                        .WithMany("SchoolUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Subject", b =>
                {
                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("Subjects")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Video", b =>
                {
                    b.HasOne("Insyte.Core.Entities.School", "School")
                        .WithMany("Videos")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Insyte.Core.Entities.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Insyte.Core.Entities.User", "UploadedBy")
                        .WithMany("UploadedVideos")
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("Teacher");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("Insyte.Core.Entities.AIModel", b =>
                {
                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("Insyte.Core.Entities.AIProvider", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Class", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Evaluation", b =>
                {
                    b.Navigation("Report");
                });

            modelBuilder.Entity("Insyte.Core.Entities.EvaluationCriteria", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Report", b =>
                {
                    b.Navigation("EmailLogs");
                });

            modelBuilder.Entity("Insyte.Core.Entities.School", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Advisors");

                    b.Navigation("Classes");

                    b.Navigation("EmailConfigs");

                    b.Navigation("Facilities");

                    b.Navigation("Languages");

                    b.Navigation("Schedules");

                    b.Navigation("Services");

                    b.Navigation("Subjects");

                    b.Navigation("Users");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Subject", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Insyte.Core.Entities.User", b =>
                {
                    b.Navigation("AdvisedSchools");

                    b.Navigation("SchoolUsers");

                    b.Navigation("UploadedVideos");
                });

            modelBuilder.Entity("Insyte.Core.Entities.Video", b =>
                {
                    b.Navigation("Evaluations");
                });
#pragma warning restore 612, 618
        }
    }
}
